### ISSUE TITLE
I have stumbled upon this in some sort of miracle 

### ISSUE THREAD

**Issue by AlecAug** [SheepTester/hello-world#10]
trump smells funny (true lol) 

Just wanted to give kudos to OP. :D

**Comment by AlecAug** [comment]
link me your paypal and ill give you 5 bucks for your work here :o

**Comment by ky28059** [comment]
@SheepTester

**Comment by SheepTester** [comment]
worrying, are you here because of deltamath? i should take it down

**Comment by AlecAug** [comment]
Yea I got here through delta math. To be fair I only found you on GitHub search libraries after sifting through about 20 projects. you are nowhere to be found on google.
