### ISSUE TITLE
BIG PROBLEM

### ISSUE THREAD

**Issue by anematode** [SheepTester/hello-world#7]
**WHAT IS**
*hello i am incompetent and didnt describe the issue*

**PROBLEM SUMMONING CEREMONY**
*hello i am incompetent and didnt share knowledge of finding oof*

**MY RUBRIC**
no evidence - oof happens automatically
approaching standards - oof happens at times
meeting expectations - oof happens when summoned
exceeding standards - oof never existed

**BLURRY SCREEN PHOTOS**
*no evidence of oof discovery*

**BIG COMPUTER**
*hello i am incompetent and failed to describe shape*

**BABY COMPUTER**
*hello i am incompetent and failed to describe photography utensil*

**FUN FACTS**
*also im incompetent and forgot to include additional information or destroy this section if i had none*

**Comment by SheepTester** [comment]
fixed

**Comment by SheepTester** [comment]
continues to be an issue, reopening

**Comment by SheepTester** [comment]
problem too old
